primerabdd/primerabdd/crm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cuentas/', views.CuentasLista.as_view(), name='ver_cuentas'),
    path('contactos/', views.ContactosPorNivel.as_view(), name='contactos'),
    path('cuentas/<int:pk>/contactos/', views.CuentasContactos.as_view(), name='cuentas_contactos'),
    path('cuentas/<int:pk>', views.CuentasDetalles.as_view(), name='cuentas_detalles'),
    path('delete/<int:pk>', views.ContactoEliminar.as_view(), name='eliminar_contacto'),
    path('create/', views.ContactoCrear.as_view(), name='crear_contacto'),
    path('create/<int:cuentaAsociada>', views.ContactoCrear.as_view(), name='crear_contacto'),
    path('contacto/<int:pk>/', views.ContactoDetalle.as_view(), name='contacto_detalle'),
    path('edit/<int:pk>', views.ContactoEditar.as_view(), name='editar_contacto'),
    path('dashboard/', views.DashBoard.as_view(),name='ver_dashboard'),
    path('carga/', views.Importador.as_view(),name='ver_importador'),
    path('upload/csv/', views.upload_csv, name='upload_csv'),
    path('download/csv/', views.download_csv, name='download_csv'),
    path('download/oportunidades/csv/', views.download_oportunidades_csv, name='download_oportunidades_csv'), 
    path('download/cuentas/csv/', views.download_cuentas_csv, name='download_cuentas_csv'),    
    path('custom/', views.CamposCustom.as_view(), name='campos_custom'),
    path('custom/createOrigin/', views.CampoCustomOrigenCrear.as_view(), name='crear_custom_origen'),
    path('custom/editOrigin/<int:pk>', views.CampoCustomOrigenEditar.as_view(), name='editar_custom_origen'),
    path('custom/deleteOrigin/<int:pk>', views.CampoCustomOrigenEliminar.as_view(), name='eliminar_custom_origen'),
    path('custom/createContactType/', views.CampoCustomTipoContactoCrear.as_view(), name='crear_custom_tipo_contacto'),
    path('custom/editContactType/<int:pk>', views.CampoCustomTipoContactoEditar.as_view(), name='editar_custom_tipo_contacto'),
    path('custom/deleteContactType/<int:pk>', views.CampoCustomTipoContactoEliminar.as_view(), name='eliminar_custom_tipo_contacto'),
    path('custom/createAccountType/', views.CampoCustomTipoCuentaCrear.as_view(), name='crear_custom_tipo_cuenta'),
    path('custom/editAccountType/<int:pk>', views.CampoCustomTipoCuentaEditar.as_view(), name='editar_custom_tipo_cuenta'),
    path('custom/deleteAccountType/<int:pk>', views.CampoCustomTipoCuentaEliminar.as_view(), name='eliminar_custom_tipo_cuenta'),
    path('custom/createOportunityState/', views.CampoCustomEstadoOportunidadCrear.as_view(), name='crear_custom_estado_oportunidad'),
    path('custom/editOportunityState/<int:pk>', views.CampoCustomEstadoOportunidadEditar.as_view(), name='editar_custom_estado_oportunidad'),
    path('custom/deleteOportunityState/<int:pk>', views.CampoCustomEstadoOportunidadEliminar.as_view(), name='eliminar_custom_estado_oportunidad'),
    path('custom/createOportunityType/', views.CampoCustomTipoOportunidadCrear.as_view(), name='crear_custom_tipo_oportunidad'),
    path('custom/editOportunityType/<int:pk>', views.CampoCustomTipoOportunidadEditar.as_view(), name='editar_custom_tipo_oportunidad'),
    path('custom/deleteOportunityType/<int:pk>', views.CampoCustomTipoOportunidadEliminar.as_view(), name='eliminar_custom_tipo_oportunidad'),
    path('cuentas/create/', views.CuentasCrear.as_view(), name='crear_cuenta'),
    path('cuentas/edit/<int:pk>', views.CuentasEditar.as_view(), name='editar_cuenta'),
    path('cuentas/delete/<int:pk>', views.CuentasEliminar.as_view(), name='eliminar_cuenta'),
    path('oportunidades/', views.OportunidadesLista.as_view(), name='ver_oportunidades'),
    path('oportunidades/create/', views.OportunidadesCrear.as_view(), name='crear_oportunidad'),
    path('oportunidades/edit/<int:pk>', views.OportunidadesEditar.as_view(), name='editar_oportunidad'),
    path('oportunidades/delete/<int:pk>', views.OportunidadesEliminar.as_view(), name='eliminar_oportunidad'),
    path('oportunidades/<int:pk>', views.OportunidadesDetalles.as_view(), name='oportunidades_detalles'),
]

primerabdd/primerabdd/primerabdd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from user_register_login import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('', include('user_register_login.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', login_required(TemplateView.as_view(template_name='home.html'), login_url="/login"), name='home'),
    url(r'^select2/', include('django_select2.urls')),
]

primerabdd/primerabdd/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from djmoney.models.fields import MoneyField
from django.db.models.signals import post_save

class Organizacion(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    nombre = models.CharField(max_length=200, blank=False, null=False)
    fecha_alta = models.DateField('fecha de alta')
    tyc_leido = models.BooleanField(blank=False, null=False, default=False)
    

    class Meta:
        verbose_name_plural = 'organizaciones'

    def __str__(self):
        return self.nombre

#####################################################
###########     CAMPOS CUSTOMIZABLES    #############
#####################################################
class CampoCustomOrigen(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    origen = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.origen)

class CampoCustomTipoContacto(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo)

class CampoCustomTipoCuenta(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo) 

class CampoCustomEstadoOportunidad(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    estado = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.estado)

class CampoCustomTipoOportunidad(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo)

#####################################################
###########     CAMPOS CUSTOMIZABLES    #############
#####################################################      

class Cuenta(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)

    calle = models.CharField(max_length=200 ,default=None, blank=True, null=True)
    numero = models.CharField(max_length=10, default=None, blank=True, null=True)
    ciudad = models.CharField(max_length=200, default=None, blank=True, null=True)
    cod_postal = models.CharField(max_length=10, default=None, blank=True, null=True)
    pais = models.CharField(max_length=200, default=None, blank=True, null=True)

    email = models.EmailField(default=None, blank=False, null=False)
    email_alternativo = models.EmailField(default=None, blank=True, null=True)

    tipo = models.ForeignKey(
            CampoCustomTipoCuenta,
            on_delete=models.PROTECT,
            blank=True,
            null=True
        )

    telefono = models.CharField(max_length=50, default=None, blank=True, null=True)
    telefono_alternativo = models.CharField(max_length=50, default=None, blank=True, null=True)
    
    web = models.CharField(max_length=200, default=None, blank=True, null=True)

    observaciones = models.TextField(default= None, blank=True, null=True)
    
    class Meta:
        constraints=[
            models.UniqueConstraint(fields=['organizacion', 'nombre'], name='nombre_cuenta_unica')
        ]


    def __str__(self):
        return self.nombre


class Contacto(models.Model):
    cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, blank=True)

    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)

    apellido = models.CharField(max_length=200, default=None, blank=False, null=False)

    documento = models.CharField(max_length=10, default=None, blank=True, null=True)

    cargo = models.CharField(max_length=200, default=None, blank=True, null=True)

    ocupacion = models.CharField(max_length=200, default=None, blank=True, null=True)

    direccion = models.CharField(max_length=200 ,default=None, blank=True, null=True)
    ciudad = models.CharField(max_length=200, default=None, blank=True, null=True)
    cod_postal = models.CharField(max_length=10, default=None, blank=True, null=True)
    
    PAISES = [
        (0,'Argentina'),
        (1,'Ecuador'),
        (2,'Peru'),
        (3,'Venezuela'),
        (4,'Mexico'),
        (5,'Panama'),
        (6,'Chile'),
        (7,'Uruguay'),
    ]

    pais = models.IntegerField(choices=PAISES, default=None, blank=True, null=True)


    fecha_de_nacimiento = models.DateField('fecha de nacimiento', blank=True, null=True)
    
    TIPOS_CONTACTO = [
        (0, 'General'),
        (1, 'Donante'),
        (2, 'Voluntario'),
        (3, 'Ambos'),
    ]

    tipo = models.IntegerField(choices=TIPOS_CONTACTO, default=0, verbose_name='Tipo de Contacto', blank=True, null=True)
    
    #LO CAMBIO A CATEGORIA DE FORMA PROVISORIA
    categoria = models.ForeignKey(
            CampoCustomTipoContacto,
            on_delete=models.PROTECT,
            blank=False,
            null=False
        )

    email = models.EmailField(default=None, blank=False, null=False)

    email_alternativo = models.EmailField(default=None, blank=True, null=True)

    OPCIONES_GENERO = [
        (0, 'Masculino'),
        (1, 'Femenino'),
        (2, 'Otro'),
    ]
    
    sexo = models.IntegerField(choices=OPCIONES_GENERO, blank=False, null=False, default=2)

    origen = models.ForeignKey(
            CampoCustomOrigen,
            on_delete=models.PROTECT,
            blank=True,
            null=True
    )

    telefono = models.CharField(max_length=50, default=None, blank=True, null=True)

    movil = models.CharField(max_length=50, default=None, blank=True, null=True)

    recibir_novedades = models.BooleanField(default=False, blank=False)

    observaciones = models.TextField(default=None, blank=True, null=True)

    es_voluntario = models.BooleanField(default=False, blank=False, null=False)

    TURNOS_VOLUNTARIOS = [
        (0, 'Mañana'),
        (1, 'Tarde'),
    ]

    turno = models.IntegerField(choices=TURNOS_VOLUNTARIOS, blank=True, null=True)

    ESTADO = [
        (0, 'Activo'),
        (1, 'Inactivo'),
    ]

    estado = models.IntegerField(choices=ESTADO, blank=True, null=True)

    LISTA_HABILIDADES = [
        (0, 'Informatica'),
        (1, 'Electricidad'),
        (2, 'Carpinteria'),
        (3, 'Otras'),
    ]

    habilidades = models.IntegerField(choices=LISTA_HABILIDADES, blank=True, null=True) 
    
    class Meta:
        constraints=[
            models.UniqueConstraint(fields=['cuenta', 'email'], name='email_contacto_unico')
        ]

    def __str__(self):
        return self.apellido


class Donante(models.Model):
    contacto = models.OneToOneField(Contacto, on_delete=models.CASCADE, blank=True, null=True)

    ESTADOS_DONANTE = [
        (0, 'Activo'),
        (1, 'De Baja'),
        (2, 'En Pausa'),
        (3, 'Completo'),
    ]

    estado = models.IntegerField(choices=ESTADOS_DONANTE, default=0, blank=False, null=False)
    
    FORMAS_PAGO = [
        (0, 'Efectivo'),
        (1, 'Tarjeta de Débito'),
        (2, 'Tarjeta de Crédito'),
        (3, 'Mercado Pago'),
        (4, 'PayPal'),
        (5, 'Otro')
    ]

    forma_de_pago = models.IntegerField(choices=FORMAS_PAGO, default=0, blank=False, null=False)
    
    #Frecuecia figura en el excel como algo obligatorio pero en la documentacion de Slack NO
    FRECUENCIAS_DONANTE = [
        (0, 'Mensual'),
        (1, 'Cada 2 Meses'),
        (2, 'Cada 3 Meses'),
        (3, 'Cada 6 Meses'),
        (4, 'Anual'),
        (5, 'Única Vez'),
    ]

    frecuencia = models.IntegerField(choices=FRECUENCIAS_DONANTE, default=0)

    monto = MoneyField(max_digits=14, decimal_places=2, default_currency='ARS')

    fecha_de_compromiso = models.DateField('fecha de compromiso')

    fecha_de_baja = models.DateField('fecha de baja')

    MOTIVOS_BAJA = [
        (0, 'No puede seguir pagando'),
        (1, 'Disconformidad'),
        (2, 'No quiere informar'),
        (3, 'Otro'),
    ]

    motivo_de_baja = models.IntegerField(choices=MOTIVOS_BAJA, default=0)

class Voluntario(models.Model):
    contacto = models.OneToOneField(Contacto, on_delete=models.CASCADE, blank=True, null=True)
    
    TURNOS_VOLUNTARIOS = [
        (0, 'Mañana'),
        (1, 'Tarde'),
    ]

    turno = models.IntegerField(choices=TURNOS_VOLUNTARIOS, blank=True, null=True)

    ESTADO = [
        (0, 'Activo'),
        (1, 'Inactivo'),
    ]

    estado = models.IntegerField(choices=ESTADO, blank=True, null=True)

    LISTA_HABILIDADES = [
        (0, 'Informatica'),
        (1, 'Electricidad'),
        (2, 'Carpinteria'),
        (3, 'Otras'),
    ]

    habilidades = models.IntegerField(choices=LISTA_HABILIDADES, blank=True, null=True)    

class Oportunidad(models.Model):
    cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, blank=False)
    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)
    
    #estado_oportunidad = models.CharField(max_length=200, default=None, blank=False, null=False)
    estado_oportunidad = models.ForeignKey(
            CampoCustomEstadoOportunidad,
            on_delete=models.PROTECT,
            blank=False,
            null=False
    )

    #tipo = models.CharField(max_length=200, default=None, blank=False, null=False)
    tipo = models.ForeignKey(
            CampoCustomTipoOportunidad,
            on_delete=models.PROTECT,
            blank=False,
            null=False
    )

    fecha = models.DateField('fecha de nacimiento')
    monto = MoneyField(max_digits=14, decimal_places=2, default_currency='ARS', default=0, blank=True)

primerabdd/primerabdd/crm/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
	  	<meta charset="utf-8">
	  	<title>Mi Primera BDD</title>
  		{% load bootstrap4 %}
        {% bootstrap_css %}
        {{ form.media.css }}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>
		<script src="{% static 'dist/sweetalert2.all.min.js' %}"></script>
		<script src="{% static 'dist/highcharts.src.js' %}"></script>
		<script src="{% static 'dist/modules/no-data-to-display.js' %}"></script>
		<script src="{% static 'dist/modules/funnel.js' %}"></script>
        <style type="text/css">
                /* navbar */
            nav {
                background-color: #007bff;
                font-size: 15px;
            }

            .container {
            	max-width: none;
            	padding: 0px;
            	margin: 0px;
            }

            nav a {
                color: white;
            }
            
            nav b {
                color: white;
            }

            h1, h2, h3 {
                color: #007bff;
            }

    	  	html, body {
		      	max-width: 100%;
		      	overflow-x: hidden;
			  }
			  
			.tdCenter {
				text-align: center;
			}

			.col-lg-2 a, .col-lg-2 input {
				width: 100%;
			}

			.nav{
			    list-style:none;
			    margin:0;
			    padding:0;
			    text-align:center;
			}
			.nav li{
			    display:inline;
			}
			.nav a{
			    display:inline-block;
			    padding:10px;
			}
        </style>
        {% if user.is_authenticated %}

	  	<nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
			<div class="container">
			  <div class="collapse navbar-collapse" id="navbarResponsive">
			    <ul class="navbar-nav ml-auto">
					<li style="z-index: 1000;" class="nav-item">
						<b>Usuario: {{ user.username }}</b>
					</li>
			    </ul>
			  </div>
			</div>
	  	</nav>

	  	<nav style="margin-top: -30px;" class="navbar navbar-expand-lg navbar-dark" id="mainNav">
			<div class="container">
			  <a href="{% url 'home' %}"><img src="{% static "logo_blanco.png" %}" alt="Not found"></a>
			  <button style="border-color: white" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			    <b>Menu</b>
			    <i class="fas fa-bars"></i>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarResponsive">
			    <ul class="navbar-nav text-uppercase mr-auto">
			      <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'ver_dashboard' %}"><b>Indicadores</b></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'contactos' %}"><b>Contactos</b></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'ver_cuentas' %}"><b>Cuentas</b></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'ver_oportunidades' %}"><b>Oportunidades</b></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'campos_custom' %}"><b>Conf. de Campos</b></a>
			      </li>
			    </ul>
			    <ul class="navbar-nav ml-auto">
				  <li class="nav-item">
			        <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><b>Cerrar Sesión</b></a>
	      		  </li>
			    </ul>
			  </div>
			</div>
	  	</nav>

        {% endif %}
        
        
        {% block body %}
        <h1>Soy el contenido de la pagina</h1>
	    {% endblock %}
          
        {% bootstrap_javascript jquery='full' %}
    {{ form.media.js }} 

    <!-- Placeholders Calle/Número/Ciudad/Código Postal -->
    <script type="text/javascript">
    	$("#id_calle").attr("placeholder", "Calle").val("").focus().blur();
    	$("#id_numero").attr("placeholder", "Altura").val("").focus().blur();

    	$("#id_ciudad").attr("placeholder", "Ciudad").val("").focus().blur();
    	$("#id_cod_postal").attr("placeholder", "Cód. Postal").val("").focus().blur();
	</script>

    <!-- Habilitar/Deshabilitad campos de voluntario -->
    <script type="text/javascript">

        if ($('#id_es_voluntario').prop('checked')) {
            $("#id_estado").prop('disabled', false);
            $("#id_turno").prop('disabled', false);
            $("#id_habilidades").prop('disabled', false);
        } else {
            $("#id_estado").prop('disabled', true);
            $("#id_turno").prop('disabled', true);
            $("#id_habilidades").prop('disabled', true);           
        }

        $('#id_es_voluntario').change(function() {
            if(this.checked) {
                $("#id_estado").prop('disabled', false);
                $("#id_turno").prop('disabled', false);
                $("#id_habilidades").prop('disabled', false);
            } else {
                $("#id_estado").prop('disabled', true);
                $("#id_turno").prop('disabled', true);
                $("#id_habilidades").prop('disabled', true);
            }     
        });
    </script>

    <script type="text/javascript">
    	
    	if($("#cuentaAsociada").val() != "" && $("#cuentaAsociada").val() != undefined){
    		$('#id_cuenta').val($("#cuentaAsociada").val()).trigger('change');
    	}

    </script>
	{% load sweetify %}
	{% sweetify %}
	</body>
</html>