primerabdd/primerabdd/crm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cuentas/', views.CuentasLista.as_view(), name='ver_cuentas'),
    path('contactos/', views.ContactosPorNivel.as_view(), name='contactos'),
    path('cuentas/<int:pk>/contactos/', views.CuentasContactos.as_view(), name='cuentas_contactos'),
    path('cuentas/<int:pk>', views.CuentasDetalles.as_view(), name='cuentas_detalles'),
    path('delete/<int:pk>', views.ContactoEliminar.as_view(), name='eliminar_contacto'),
    path('create/', views.ContactoCrear.as_view(), name='crear_contacto'),
    path('create/<int:cuentaAsociada>', views.ContactoCrear.as_view(), name='crear_contacto'),
    path('contacto/<int:pk>/', views.ContactoDetalle.as_view(), name='contacto_detalle'),
    path('edit/<int:pk>', views.ContactoEditar.as_view(), name='editar_contacto'),
    path('dashboard/', views.DashBoard.as_view(),name='ver_dashboard'),
    path('carga/', views.Importador.as_view(),name='ver_importador'),
    path('upload/csv/', views.upload_csv, name='upload_csv'),
    path('download/csv/', views.download_csv, name='download_csv'),
    path('download/oportunidades/csv/', views.download_oportunidades_csv, name='download_oportunidades_csv'), 
    path('download/cuentas/csv/', views.download_cuentas_csv, name='download_cuentas_csv'),    
    path('custom/', views.CamposCustom.as_view(), name='campos_custom'),
    path('custom/createOrigin/', views.CampoCustomOrigenCrear.as_view(), name='crear_custom_origen'),
    path('custom/editOrigin/<int:pk>', views.CampoCustomOrigenEditar.as_view(), name='editar_custom_origen'),
    path('custom/deleteOrigin/<int:pk>', views.CampoCustomOrigenEliminar.as_view(), name='eliminar_custom_origen'),
    path('custom/createContactType/', views.CampoCustomTipoContactoCrear.as_view(), name='crear_custom_tipo_contacto'),
    path('custom/editContactType/<int:pk>', views.CampoCustomTipoContactoEditar.as_view(), name='editar_custom_tipo_contacto'),
    path('custom/deleteContactType/<int:pk>', views.CampoCustomTipoContactoEliminar.as_view(), name='eliminar_custom_tipo_contacto'),
    path('custom/createAccountType/', views.CampoCustomTipoCuentaCrear.as_view(), name='crear_custom_tipo_cuenta'),
    path('custom/editAccountType/<int:pk>', views.CampoCustomTipoCuentaEditar.as_view(), name='editar_custom_tipo_cuenta'),
    path('custom/deleteAccountType/<int:pk>', views.CampoCustomTipoCuentaEliminar.as_view(), name='eliminar_custom_tipo_cuenta'),
    path('custom/createOportunityState/', views.CampoCustomEstadoOportunidadCrear.as_view(), name='crear_custom_estado_oportunidad'),
    path('custom/editOportunityState/<int:pk>', views.CampoCustomEstadoOportunidadEditar.as_view(), name='editar_custom_estado_oportunidad'),
    path('custom/deleteOportunityState/<int:pk>', views.CampoCustomEstadoOportunidadEliminar.as_view(), name='eliminar_custom_estado_oportunidad'),
    path('custom/createOportunityType/', views.CampoCustomTipoOportunidadCrear.as_view(), name='crear_custom_tipo_oportunidad'),
    path('custom/editOportunityType/<int:pk>', views.CampoCustomTipoOportunidadEditar.as_view(), name='editar_custom_tipo_oportunidad'),
    path('custom/deleteOportunityType/<int:pk>', views.CampoCustomTipoOportunidadEliminar.as_view(), name='eliminar_custom_tipo_oportunidad'),
    path('cuentas/create/', views.CuentasCrear.as_view(), name='crear_cuenta'),
    path('cuentas/edit/<int:pk>', views.CuentasEditar.as_view(), name='editar_cuenta'),
    path('cuentas/delete/<int:pk>', views.CuentasEliminar.as_view(), name='eliminar_cuenta'),
    path('oportunidades/', views.OportunidadesLista.as_view(), name='ver_oportunidades'),
    path('oportunidades/create/', views.OportunidadesCrear.as_view(), name='crear_oportunidad'),
    path('oportunidades/edit/<int:pk>', views.OportunidadesEditar.as_view(), name='editar_oportunidad'),
    path('oportunidades/delete/<int:pk>', views.OportunidadesEliminar.as_view(), name='eliminar_oportunidad'),
    path('oportunidades/<int:pk>', views.OportunidadesDetalles.as_view(), name='oportunidades_detalles'),
]

primerabdd/primerabdd/primerabdd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from user_register_login import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('', include('user_register_login.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', login_required(TemplateView.as_view(template_name='home.html'), login_url="/login"), name='home'),
    url(r'^select2/', include('django_select2.urls')),
]

primerabdd/primerabdd/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from djmoney.models.fields import MoneyField
from django.db.models.signals import post_save

class Organizacion(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    nombre = models.CharField(max_length=200, blank=False, null=False)
    fecha_alta = models.DateField('fecha de alta')
    tyc_leido = models.BooleanField(blank=False, null=False, default=False)
    

    class Meta:
        verbose_name_plural = 'organizaciones'

    def __str__(self):
        return self.nombre

#####################################################
###########     CAMPOS CUSTOMIZABLES    #############
#####################################################
class CampoCustomOrigen(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    origen = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.origen)

class CampoCustomTipoContacto(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo)

class CampoCustomTipoCuenta(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo) 

class CampoCustomEstadoOportunidad(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    estado = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.estado)

class CampoCustomTipoOportunidad(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50, default=None, blank=True, null=True)

    def __str__(self):
        return (self.tipo)

#####################################################
###########     CAMPOS CUSTOMIZABLES    #############
#####################################################      

class Cuenta(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)

    calle = models.CharField(max_length=200 ,default=None, blank=True, null=True)
    numero = models.CharField(max_length=10, default=None, blank=True, null=True)
    ciudad = models.CharField(max_length=200, default=None, blank=True, null=True)
    cod_postal = models.CharField(max_length=10, default=None, blank=True, null=True)
    pais = models.CharField(max_length=200, default=None, blank=True, null=True)

    email = models.EmailField(default=None, blank=False, null=False)
    email_alternativo = models.EmailField(default=None, blank=True, null=True)

    tipo = models.ForeignKey(
            CampoCustomTipoCuenta,
            on_delete=models.PROTECT,
            blank=True,
            null=True
        )

    telefono = models.CharField(max_length=50, default=None, blank=True, null=True)
    telefono_alternativo = models.CharField(max_length=50, default=None, blank=True, null=True)
    
    web = models.CharField(max_length=200, default=None, blank=True, null=True)

    observaciones = models.TextField(default= None, blank=True, null=True)
    
    class Meta:
        constraints=[
            models.UniqueConstraint(fields=['organizacion', 'nombre'], name='nombre_cuenta_unica')
        ]


    def __str__(self):
        return self.nombre


class Contacto(models.Model):
    cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, blank=True)

    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)

    apellido = models.CharField(max_length=200, default=None, blank=False, null=False)

    documento = models.CharField(max_length=10, default=None, blank=True, null=True)

    cargo = models.CharField(max_length=200, default=None, blank=True, null=True)

    ocupacion = models.CharField(max_length=200, default=None, blank=True, null=True)

    direccion = models.CharField(max_length=200 ,default=None, blank=True, null=True)
    ciudad = models.CharField(max_length=200, default=None, blank=True, null=True)
    cod_postal = models.CharField(max_length=10, default=None, blank=True, null=True)
    
    PAISES = [
        (0,'Argentina'),
        (1,'Ecuador'),
        (2,'Peru'),
        (3,'Venezuela'),
        (4,'Mexico'),
        (5,'Panama'),
        (6,'Chile'),
        (7,'Uruguay'),
    ]

    pais = models.IntegerField(choices=PAISES, default=None, blank=True, null=True)


    fecha_de_nacimiento = models.DateField('fecha de nacimiento', blank=True, null=True)
    
    TIPOS_CONTACTO = [
        (0, 'General'),
        (1, 'Donante'),
        (2, 'Voluntario'),
        (3, 'Ambos'),
    ]

    tipo = models.IntegerField(choices=TIPOS_CONTACTO, default=0, verbose_name='Tipo de Contacto', blank=True, null=True)
    
    #LO CAMBIO A CATEGORIA DE FORMA PROVISORIA
    categoria = models.ForeignKey(
            CampoCustomTipoContacto,
            on_delete=models.PROTECT,
            blank=False,
            null=False
        )

    email = models.EmailField(default=None, blank=False, null=False)

    email_alternativo = models.EmailField(default=None, blank=True, null=True)

    OPCIONES_GENERO = [
        (0, 'Masculino'),
        (1, 'Femenino'),
        (2, 'Otro'),
    ]
    
    sexo = models.IntegerField(choices=OPCIONES_GENERO, blank=False, null=False, default=2)

    origen = models.ForeignKey(
            CampoCustomOrigen,
            on_delete=models.PROTECT,
            blank=True,
            null=True
    )

    telefono = models.CharField(max_length=50, default=None, blank=True, null=True)

    movil = models.CharField(max_length=50, default=None, blank=True, null=True)

    recibir_novedades = models.BooleanField(default=False, blank=False)

    observaciones = models.TextField(default=None, blank=True, null=True)

    es_voluntario = models.BooleanField(default=False, blank=False, null=False)

    TURNOS_VOLUNTARIOS = [
        (0, 'Mañana'),
        (1, 'Tarde'),
    ]

    turno = models.IntegerField(choices=TURNOS_VOLUNTARIOS, blank=True, null=True)

    ESTADO = [
        (0, 'Activo'),
        (1, 'Inactivo'),
    ]

    estado = models.IntegerField(choices=ESTADO, blank=True, null=True)

    LISTA_HABILIDADES = [
        (0, 'Informatica'),
        (1, 'Electricidad'),
        (2, 'Carpinteria'),
        (3, 'Otras'),
    ]

    habilidades = models.IntegerField(choices=LISTA_HABILIDADES, blank=True, null=True) 
    
    class Meta:
        constraints=[
            models.UniqueConstraint(fields=['cuenta', 'email'], name='email_contacto_unico')
        ]

    def __str__(self):
        return self.apellido


class Donante(models.Model):
    contacto = models.OneToOneField(Contacto, on_delete=models.CASCADE, blank=True, null=True)

    ESTADOS_DONANTE = [
        (0, 'Activo'),
        (1, 'De Baja'),
        (2, 'En Pausa'),
        (3, 'Completo'),
    ]

    estado = models.IntegerField(choices=ESTADOS_DONANTE, default=0, blank=False, null=False)
    
    FORMAS_PAGO = [
        (0, 'Efectivo'),
        (1, 'Tarjeta de Débito'),
        (2, 'Tarjeta de Crédito'),
        (3, 'Mercado Pago'),
        (4, 'PayPal'),
        (5, 'Otro')
    ]

    forma_de_pago = models.IntegerField(choices=FORMAS_PAGO, default=0, blank=False, null=False)
    
    #Frecuecia figura en el excel como algo obligatorio pero en la documentacion de Slack NO
    FRECUENCIAS_DONANTE = [
        (0, 'Mensual'),
        (1, 'Cada 2 Meses'),
        (2, 'Cada 3 Meses'),
        (3, 'Cada 6 Meses'),
        (4, 'Anual'),
        (5, 'Única Vez'),
    ]

    frecuencia = models.IntegerField(choices=FRECUENCIAS_DONANTE, default=0)

    monto = MoneyField(max_digits=14, decimal_places=2, default_currency='ARS')

    fecha_de_compromiso = models.DateField('fecha de compromiso')

    fecha_de_baja = models.DateField('fecha de baja')

    MOTIVOS_BAJA = [
        (0, 'No puede seguir pagando'),
        (1, 'Disconformidad'),
        (2, 'No quiere informar'),
        (3, 'Otro'),
    ]

    motivo_de_baja = models.IntegerField(choices=MOTIVOS_BAJA, default=0)

class Voluntario(models.Model):
    contacto = models.OneToOneField(Contacto, on_delete=models.CASCADE, blank=True, null=True)
    
    TURNOS_VOLUNTARIOS = [
        (0, 'Mañana'),
        (1, 'Tarde'),
    ]

    turno = models.IntegerField(choices=TURNOS_VOLUNTARIOS, blank=True, null=True)

    ESTADO = [
        (0, 'Activo'),
        (1, 'Inactivo'),
    ]

    estado = models.IntegerField(choices=ESTADO, blank=True, null=True)

    LISTA_HABILIDADES = [
        (0, 'Informatica'),
        (1, 'Electricidad'),
        (2, 'Carpinteria'),
        (3, 'Otras'),
    ]

    habilidades = models.IntegerField(choices=LISTA_HABILIDADES, blank=True, null=True)    

class Oportunidad(models.Model):
    cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, blank=False)
    nombre = models.CharField(max_length=200, default=None, blank=False, null=False)
    
    #estado_oportunidad = models.CharField(max_length=200, default=None, blank=False, null=False)
    estado_oportunidad = models.ForeignKey(
            CampoCustomEstadoOportunidad,
            on_delete=models.PROTECT,
            blank=False,
            null=False
    )

    #tipo = models.CharField(max_length=200, default=None, blank=False, null=False)
    tipo = models.ForeignKey(
            CampoCustomTipoOportunidad,
            on_delete=models.PROTECT,
            blank=False,
            null=False
    )

    fecha = models.DateField('fecha de nacimiento')
    monto = MoneyField(max_digits=14, decimal_places=2, default_currency='ARS', default=0, blank=True)

primerabdd/primerabdd/crm/templates/crm/confirmar_eliminacion.html
{% extends "base.html" %}

{% block body %}
<h1>Eliminar {{ contacto.nombre }}</h1>
<form  method="post">
{% csrf_token %}
¿Está seguro de que desea eliminar este contacto?
<input type="submit" value="Si"/>
</form>
{% endblock %}

primerabdd/primerabdd/crm/templates/crm/creacion_contacto.html
{% extends "base.html" %}

{% block body %}

<style type="text/css">

    .row {
        padding-bottom: 20px;
    }

    label {
        margin-bottom: 0px;
    }
    
    .col-lg-4 input, .col-lg-4 select {
        width: 90%;
    }

    .col-lg-4 input {

    }

    .col-lg-4 .btn {
        width: 50%;
    }

    p {
        margin-top: 10px;
        margin-bottom: 5px;
    }

    #id_ciudad {
        width: 65%;
    }

    #id_numero, #id_cod_postal {
        width: 25%
    }

    #id_observaciones {
        width: 97%;
        height: 100px;
    }

</style>

<form style="padding: 15px;" action="" method="post">
    {% csrf_token %}

    <h2> {{ "Gestión de Contactos / "|add:accion }} </h2>

    <input id="cuentaAsociada" type="hidden" value="{{ request.resolver_match.kwargs.cuentaAsociada }}">

    <div class="row">
        <div class="col-lg-4">
            {{ form.nombre.errors }}
            <label for="{{ form.nombre.id_for_label }}">Nombre *</label>
            {{ form.nombre }}
        </div>

        <div class="col-lg-4">
            {{ form.apellido.errors }}
            <label for="{{ form.apellido.id_for_label }}">Apellido *</label>
            {{ form.apellido }}
        </div>

        <div class="col-lg-4">
            {{ form.sexo.errors }}
            <label for="{{ form.sexo.id_for_label }}">Género</label>
            {{ form.sexo }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            {{ form.cargo.errors }}
            <label for="{{ form.cargo.id_for_label }}">Cargo</label>
            {{ form.cargo }}
        </div>

        <div class="col-lg-4">
            {{ form.documento.errors }}
            <label for="{{ form.documento.id_for_label }}">Documento</label>
            {{ form.documento }}
        </div>

        <div class="col-lg-4">
            {{ form.fecha_de_nacimiento.errors }}
            <label for="{{ form.fecha_de_nacimiento.id_for_label }}">Fecha de nacimiento</label>
            {{ form.fecha_de_nacimiento }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            {{ form.ocupacion.errors }}
            <label for="{{ form.ocupacion.id_for_label }}">Ocupación</label>
            {{ form.ocupacion }}
        </div>

        <div class="col-lg-4">
            {{ form.cuenta.errors }}
            <label for="{{ form.cuenta.id_for_label }}">Cuenta</label>
            {{ form.cuenta }}
        </div>

        <div class="col-lg-4" style="white-space:nowrap">
            {{ form.es_voluntario.errors }}
            <label for="{{ form.es_voluntario.id_for_label }}">Perfil Voluntariado</label>
            {{ form.es_voluntario }}
            <div>
                {{ form.estado }}
            </div>
        </div>
        
    </div>


    <div class="row">
        <div class="col-lg-4">
            <label for="{{ form.email.id_for_label }}">Email *</label>
            {{ form.email }}
        </div>

        <div class="col-lg-4">
            {{ form.email_alternativo.errors }}
            <label for="{{ form.email_alternativo.id_for_label }}">Email alternativo</label>
            {{ form.email_alternativo }}
        </div>

        <div class="col-lg-4">
            {{ form.turno.errors }}
            <label for="{{ form.turno.id_for_label }}"></label>
            <div>{{ form.turno }}</div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            {{ form.telefono.errors }}
            <label for="{{ form.telefono.id_for_label }}">Teléfono</label>
            {{ form.telefono }}
        </div>

        <div class="col-lg-4">
            {{ form.direccion.errors }}
            <label for="{{ form.direccion.id_for_label }}">Dirección</label><br>
            {{ form.direccion }}
        </div> 

        <div class="col-lg-4">
            {{ form.habilidades.errors }}
            <label for="{{ form.habilidades.id_for_label }}"></label>
            <div>{{ form.habilidades }}</div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            {{ form.ciudad.errors }}
            <label for="{{ form.ciudad.id_for_label }}">Ciudad</label><br>
            {{ form.ciudad }}
            {{ form.cod_postal }}
        </div> 
        <div class="col-lg-4">
            {{ form.movil.errors }}
            <label for="{{ form.telefono.id_for_label }}">Móvil</label>
            {{ form.movil }}
        </div> 
        <div class="col-lg-4">
            {{ form.pais.errors }}
            <label for="{{ form.pais.id_for_label }}">País</label><br>
            {{ form.pais }}
        </div> 
    </div>
    <div class="row">
        <div class="col-lg-4">
            {{ form.origen.errors }}
            <label for="{{ form.origen.id_for_label }}">Origen</label>
            {{ form.origen }}
        </div>

        <div class="col-lg-4">
            {{ form.categoria.errors }}
            <label for="{{ form.tipo.id_for_label }}">Tipo *</label><br>
            {{ form.categoria }}
        </div>

        <div class="col-lg-4">
            {{ form.recibir_novedades.errors }}
            <label for="{{ form.recibir_novedades.id_for_label }}">¿Desea recibir novedades?</label>
            {{ form.recibir_novedades }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {{ form.observaciones.errors }}
            <label for="{{ form.observaciones.id_for_label }}">Observaciones</label><br>
            {{ form.observaciones }}
        </div>
    </div>

    <div class="row" style="padding-right: 50px; padding-left: 10px;">
        <div class="col-6 col-sm-6 col-md-6 col-lg-6">
        </div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2"></div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2" style="padding-left: 2px; padding-right: 2px;">
            <a class="btn btn-secondary" style="margin-top: 10px; margin-right: 40px;" href="/contactos">Volver</a>
        </div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2" style="padding-left: 2px; padding-right: 2px;">
            <input class="btn btn-success" type="submit" value="Guardar" style="margin-top: 10px; margin-right: 40px;" /> 
        </div>
    </div>

</form>

{% endblock %}

primerabdd/primerabdd/crm/templates/crm/creacion_cuenta.html
{% extends "base.html" %}

{% block body %}

<style type="text/css">

    .row {
        padding-bottom: 20px;
    }

    label {
        margin-bottom: 0px;
    }
    
    .col-lg-4 input, .col-lg-4 select {
        width: 90%;
    }

    .col-lg-4 .btn {
        width: 50%;
    }

    p {
        margin-top: 10px;
        margin-bottom: 5px;
    }

    #id_observaciones {
        width: 97%;
        height: 100px;
    }

</style>

<form style="padding: 15px;" action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <h2>Gestión de Cuentas</h2>

    <div class="row">
        <div class="col-lg-4">
            <label for="{{ form.nombre.id_for_label }}">Nombre *</label>
            {{ form.nombre }}
        </div>

        <div class="col-lg-4">
            {{ form.calle.errors }}
            <label for="{{ form.calle.id_for_label }}">Dirección</label><br>
            {{ form.calle }}
        </div>

        <div class="col-lg-4">
            {{ form.pais.errors }}
            <label for="{{ form.sexo.id_for_label }}">País</label><br>
            {{ form.pais }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            {{ form.email.errors }}
            <label for="{{ form.email.id_for_label }}">Email *</label>
            {{ form.email }}
        </div>

        <div class="col-lg-4">
            {{ form.email_alternativo.errors }}
            <label for="{{ form.email_alternativo.id_for_label }}">Email Alternativo</label>
            {{ form.email_alternativo }}
        </div>

        <div class="col-lg-4">
            {{ form.tipo.errors }}
            <label for="{{ form.tipo.id_for_label }}">Tipo</label><br>
            {{ form.tipo }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            {{ form.telefono.errors }}
            <label for="{{ form.telefono.id_for_label }}">Teléfono</label>
            {{ form.telefono }}
        </div>

        <div class="col-lg-4">
            {{ form.telefono_alternativo.errors }}
            <label for="{{ form.telefono_alternativo.id_for_label }}">Tel. Alternativo</label>
            {{ form.telefono_alternativo }}
        </div>

        <div class="col-lg-4">
            {{ form.web.errors }}
            <label for="{{ form.web.id_for_label }}">Web</label><br>
            {{ form.web }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {{ form.observaciones.errors }}
            <label for="{{ form.observaciones.id_for_label }}">Observaciones</label><br>
            {{ form.observaciones }}
        </div>
    </div>

    <div class="row" style="padding-right: 50px; padding-left: 10px;">
        <div class="col-6 col-sm-6 col-md-6 col-lg-6">
        </div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2"></div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2" style="padding-left: 2px; padding-right: 2px;">
            <a class="btn btn-secondary" style="margin-top: 10px; margin-right: 40px;" href="/cuentas">Volver</a>
        </div>
        <div class="col-2 col-sm-2 col-md-2 col-lg-2" style="padding-left: 2px; padding-right: 2px;">
            <input class="btn btn-success" type="submit" value="Guardar" style="margin-top: 10px; margin-right: 40px;" /> 
        </div>
    </div>

</form>

{% endblock %}

primerabdd/primerabdd/crm/templates/crm/crear_custom.html
{% extends "base.html" %}

{% block body %}
<form action="" method="POST"> 
    {% csrf_token %}
    {{ form.non_field_errors }}

    <h2> {{ "Gestion Campos Custom /" |add:accion }}</h2>
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Agregar" />
</form>
{% endblock %}

primerabdd/primerabdd/crm/templates/crm/eliminar_campo_custom.html
{% extends "base.html" %}

{% block body %}
<h1>Eliminar el campo custom "{{ nombre }}"</h1>
<form  method="post">
{% csrf_token %}
¿Está seguro de que desea eliminar este campo?
<input type="submit" value="Si"/>
</form>
{% if messages %}
   {% for message in messages %}
		<script>
		    alert('{{ message }}');
		</script>
   {% endfor %}
{% endif %}
{% endblock %}

primerabdd/primerabdd/crm/templates/crm/uploader.html
{% extends "base.html" %}

{% block body %}
<h1>Importar contactos</h1>
<form action="{% url "upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
{% csrf_token %}
<div class="form-group">
    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label"> </label>
    <div class="col-md-8">
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
    </div>                    
</div>
<div class="form-group">                    
    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Subir </button>
    </div> 
</div>
</form>
{% if messages %}
   {% for message in messages %}
		<script>
		    alert('{{ message }}');
		</script>
   {% endfor %}
{% endif %}
{% endblock %}